### ISSUE TITLE
Mismatched C++ standard version between this template and pmp-library.

### ISSUE THREAD

**Issue by hndm** [pmp-library/pmp-template#3]
Building on Unix, Mac or Emscripten does not work because the updated PMP library version requires `std::filesystem` which is only supported since c++17.
Updating the c++ standard version from c++11 to c++17 fixes the problem.

I only tested this on Linux Mint 21.2 but it should work on all the platforms mentioned.

**Comment by dsieger** [comment]
Thanks for spotting!
